### ISSUE TITLE
Prevent HTML tag escape

### ISSUE THREAD

**Issue by ptorrent** [totaljs/Tangular#16]
Hello,

Is there a way to prevent HTML tag to be escaped ?

```
Tangular.render('fdsfsdfsd {{ok}}',{ ok : '<span style="color:red;">yes</span>'})
18:33:18.463 'fdsfsdfsd <span>&lt;span style=&quot;color:red;&quot;&gt;yes&lt;/span&gt;</span>'
```

Thanks for your help

**Comment by petersirka** [comment]
It's easy: `{{ ok | raw }}`. More information here: https://docs.totaljs.com/components/40d06002lm50c/

**Comment by ptorrent** [comment]
awesome support, working well

Thanks
