### ISSUE TITLE
Prefer tangular than Tangular

### ISSUE THREAD

**Issue by Darmody** [totaljs/Tangular#8]
![2017-02-17 16 05 54](https://cloud.githubusercontent.com/assets/6788752/23057422/12554d7e-f52b-11e6-9602-272fc55d1a17.png)

**Comment by petersirka** [comment]
Hi, it works correctly:

![image](https://cloud.githubusercontent.com/assets/2414252/23057553/f6e90470-f4f0-11e6-8001-49f7ad7f06e9.png)

I have tested it.

**Comment by Darmody** [comment]
Hm... But export function should be lower.

**Comment by petersirka** [comment]
I don't understand, for my it works correctly...

**Comment by molda** [comment]
Hi @Darmody the error comes from ESLint's eslint-plugin-import rule so it's actualy not a runtime error nor it's a syntax error or anything else. The rule just doesn't like it but the code will work anyways.

The naming convetion is entirely up to the writer of the code and can't be enforced.

You should be able to disable the ESLint for the line with `require('tangular');`  using following snippet
```javascript
var Tangular = require('tangular'); // eslint-disable-line
```

**Comment by Darmody** [comment]
In my opnion, thinking `Tangular` is inconsistent, because package name is `tangular`.

@molda just don't make eslint green without disabling that rule, lol.

**Comment by petersirka** [comment]
@Darmody `tangular` has own reasons why is called `tangular`. This is not my fiction, it works correctly and this is important, nothing more.
