### ISSUE TITLE
Redundant empty line generated when "if" condition not filled

### ISSUE THREAD

**Issue by Darmody** [totaljs/Tangular#9]

**Comment by petersirka** [comment]
Can you write a simple demo?

**Comment by Darmody** [comment]
``` html
<div> A </div>
 {{if false }}
   do some things
 {{fi}}
<div> B </div>
```

it will output to

```html
  <div> A </div>
                                       // here is an empty line
  <div> B </div>
```

**Comment by petersirka** [comment]
Yes, because:

```html
<div> A </div>\n
 {{if false }}
   do some things
 {{fi}}\n
<div> B </div>
```

__but you can write it as__:

```html
<div> A </div> {{if false }}
   do some things
 {{fi}}<div> B </div>
```

Tangular doesn't minify the output. I use __Tangular__ (sometimes) in `<pre` tag and here are very important white spaces, so therefore....

**Comment by Darmody** [comment]
But `{{if false}}` don't mean anything in output. I think it should not take up a line.

And it is a different thing from minify.

**Comment by petersirka** [comment]
I'll look into it this weekend.

**Comment by Darmody** [comment]
@petersirka That's cool!

**Comment by petersirka** [comment]
I have fixed it.
Try to install latest version from NPM.
